name: "datadex"
version: "1.0.0"
config-version: 2

profile: "default"

target-path: "target"
clean-targets:
  - "logs"
  - "target"
  - "database"
  - "dbt_packages"

models:
  datadex:
    +materialized: external
