[project]
name = "datadex"
version = "1.0.0"
dependencies = [
    "altair",
    "dagster",
    "dagster-dbt",
    "dbt-sqlserver",
    "dbt-core",
    "dbt-duckdb",
    "duckdb",
    "frictionless",
    "ipykernel",
    "itables",
    "ipywidgets",
    "matplotlib",
    "nbclient",
    "nbformat",
    "numpy",
    "pandas==2.0.3", # clash with duckdb, pin to 2.0.x
    "polars",
    "pyarrow",
    "regex",
    "tqdm",
    "vegafusion[embed]",
    "zstandard",
]

requires-python = ">=3.10, <3.12"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
dev = ["dagit", "shandy-sqlfmt[jinjafmt]"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["datadex"]

[tool.dagster]
module_name = "datadex"
