version: 2

sources:
  - name: ethereum
    tables:
      - name: blocks
        meta:
          external_location: "parquet_scan('s3://aws-public-blockchain/v1.0/eth/blocks/*/*.parquet', HIVE_PARTITIONING=1)"
      - name: logs
        meta:
          external_location: "parquet_scan('s3://aws-public-blockchain/v1.0/eth/logs/*/*.parquet', HIVE_PARTITIONING=1)"
