version: 2

sources:
  - name: web
    tables:
      - name: energy
        description: Key energy metrics maintained by Our World in Data
        meta:
          source: https://ourworldindata.org/energy
          external_location: https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-data.csv
      - name: co2_global_trend
        description: Trends in Atmospheric Carbon Dioxide
        meta:
          source: https://gml.noaa.gov
          external_location: https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_trend_gl.csv

  - name: threatened_animal_species
    schema: main
    config:
      plugin: frictionless
      package: https://raw.githubusercontent.com/datonic/threatened-animal-species/main/datapackage.yaml
    tables:
      - name: threatened_species
